<?php
namespace Opencart\Catalog\Controller\Extension\WebskySeo\Feed;
use Opencart\System\Library\Extension\WebskySeo\Settings;
use Opencart\System\Library\Extension\WebskySeo\Text;
class Sitemap extends \Opencart\System\Engine\Controller {
 public function index(): void {
  $s=Settings::read($this->config);if(!$s['status']||!$s['sitemap']){$this->response->addHeader('HTTP/1.1 404 Not Found');return;}$lang=(string)$this->config->get('config_language');$store=(int)$this->config->get('config_store_id');$urls=[['loc'=>$this->url->link('common/home',['language'=>$lang],true),'priority'=>'1.0','changefreq'=>'daily']];
  $rows=$this->db->query('SELECT p.product_id,p.date_modified FROM `'.DB_PREFIX.'product` p JOIN `'.DB_PREFIX.'product_to_store` s ON s.product_id=p.product_id AND s.store_id='.$store." WHERE p.status=1 AND p.date_available<=NOW() ORDER BY p.product_id")->rows;foreach($rows as $r)$urls[]=['loc'=>$this->url->link('product/product',['language'=>$lang,'product_id'=>(int)$r['product_id']],true),'lastmod'=>substr((string)$r['date_modified'],0,10),'priority'=>'0.8','changefreq'=>'weekly'];
  $rows=$this->db->query('SELECT c.category_id FROM `'.DB_PREFIX.'category` c JOIN `'.DB_PREFIX.'category_to_store` s ON s.category_id=c.category_id AND s.store_id='.$store." WHERE c.status=1 ORDER BY c.category_id")->rows;foreach($rows as $r)$urls[]=['loc'=>$this->url->link('product/category',['language'=>$lang,'path'=>(int)$r['category_id']],true),'priority'=>'0.7','changefreq'=>'weekly'];
  $rows=$this->db->query('SELECT m.manufacturer_id FROM `'.DB_PREFIX.'manufacturer` m JOIN `'.DB_PREFIX.'manufacturer_to_store` s ON s.manufacturer_id=m.manufacturer_id AND s.store_id='.$store.' ORDER BY m.manufacturer_id')->rows;foreach($rows as $r)$urls[]=['loc'=>$this->url->link('product/manufacturer.info',['language'=>$lang,'manufacturer_id'=>(int)$r['manufacturer_id']],true),'priority'=>'0.5','changefreq'=>'monthly'];
  $rows=$this->db->query('SELECT i.information_id FROM `'.DB_PREFIX.'information` i JOIN `'.DB_PREFIX.'information_to_store` s ON s.information_id=i.information_id AND s.store_id='.$store.' WHERE i.status=1 ORDER BY i.information_id')->rows;foreach($rows as $r)$urls[]=['loc'=>$this->url->link('information/information',['language'=>$lang,'information_id'=>(int)$r['information_id']],true),'priority'=>'0.4','changefreq'=>'monthly'];
  $xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";foreach($urls as $u){$xml.='  <url><loc>'.htmlspecialchars((string)$u['loc'],ENT_QUOTES|ENT_XML1,'UTF-8').'</loc>';if(!empty($u['lastmod'])&&$u['lastmod']!=='0000-00-00')$xml.='<lastmod>'.Text::escape($u['lastmod']).'</lastmod>';$xml.="<changefreq>{$u['changefreq']}</changefreq><priority>{$u['priority']}</priority></url>\n";}$xml.='</urlset>';$this->response->addHeader('Content-Type: application/xml; charset=utf-8');$this->response->setOutput($xml);
 }
}